AUTH_EXPIRY_TIME_SECONDS = 2592000  # 30 days
AUTH_TOKEN_PREFIX = "TOKEN:"
JWT_ENCODE_ALGORITHM = "HS256"

PSWD_RESET_PREFIX = "PSWD_RESET_"

EXPERIENCE_IMAGE_DIR = "experience_images"

EMAIL_TEMPLATES_DIR = "app/resources/email_templates"

